### ISSUE TITLE
配置代理启动报错

### ISSUE THREAD

**Issue by hxgqh** [Pcject/chatbot-ui-by-proxy#2]
/app/start_by_proxy.sh:3
sed -i "s/socks4[[:space:]]\+127\.0\.0\.1[[:space:]]\+9050/${PROXYCHAINS_PROXY}/g" /tmp/proxychains.conf
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string

**Comment by Pcject** [comment]
提供下你的配置

**Comment by hxgqh** [comment]
```yaml
version: "3"
services:
  chatbot-ui:
    image: pcject/chatbot-ui:main
    container_name: chatbot-ui
    hostname: chatbot-ui
    restart: always
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY=xxxxxxxxxxxx
      - PROXYCHAINS_PROXY="http 192.168.1.9 33210"
    ports:
      - '13000:3000'
```
